# Generated by Django 6.1.1 on 2026-09-21 07:12

from django.db import migrations

REGULATOR = "Regulator"
DATA_TEAM = "Data Team"


def create_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.get_or_create(name=REGULATOR)
    Group.objects.get_or_create(name=DATA_TEAM)


def delete_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name__in=[REGULATOR, DATA_TEAM]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RunPython(create_groups, delete_groups),
    ]
