# Generated by Django 6.1.1 on 2026-09-23 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tier', models.CharField(choices=[('tertiary', 'Tertiary (Zonal/National Referral Hospital)'), ('regional', 'Regional Referral Hospital'), ('district', 'District Hospital'), ('health_centre', 'Health Centre'), ('dispensary', 'Dispensary')], max_length=20)),
                ('ownership', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('region_name', models.CharField(blank=True, max_length=200)),
                ('district_name', models.CharField(blank=True, max_length=200)),
                ('source', models.CharField(blank=True, help_text='Where this record came from', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'health facilities',
                'indexes': [models.Index(fields=['tier'], name='facilities__tier_311761_idx'), models.Index(fields=['ownership'], name='facilities__ownersh_4b67e3_idx')],
            },
        ),
    ]
