# Generated by Django 6.1.1 on 2026-09-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthfacility',
            name='facility_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='healthfacility',
            name='tier',
            field=models.CharField(choices=[('tertiary', 'Tertiary (Zonal/National Referral Hospital)'), ('regional', 'Regional Referral Hospital'), ('district', 'District Hospital'), ('health_centre', 'Health Centre'), ('dispensary', 'Dispensary'), ('laboratory', 'Standalone Medical Laboratory')], max_length=20),
        ),
    ]
