# Generated by Django 6.1.1 on 2026-09-21 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('geometry', models.JSONField(help_text="GeoJSON geometry for this region's boundary")),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('geometry', models.JSONField(help_text="GeoJSON geometry for this district's boundary")),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='geo.region')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('geometry', models.JSONField(help_text="GeoJSON geometry for this ward's boundary")),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='geo.district')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
